trigger:
  branches:
    include:
      - main
  tags:
    include:
    - '*'
pr:
- main

variables:
- group: docfx-v2-pipeline-kv

jobs:
- job: build
  strategy:
    matrix:
      linux:
        os: 'ubuntu-latest'
      mac:
        os: 'macos-latest'
      windows:
        os: 'windows-latest'
  pool:
    vmImage: $(os)

  steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 6.0.x

  - script: dotnet test -c Release
    displayName: dotnet test

- job: publish
  dependsOn: build
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 6.0.x

  - task: UseDotNet@2
    inputs:
      packageType: sdk
      version: 2.1.x # for ESRPCodeSigning

  - script: dotnet test -c Release
    displayName: dotnet test

  - script: >
      dotnet pack -c Release -o $(Agent.TempDirectory)/nuget
      /p:Version=$(Build.SourceBranchName)
      /p:InformationalVersion=$(Build.SourceBranchName)-$(Build.SourceVersion)
    displayName: dotnet pack

  - task: EsrpCodeSigning@1
    displayName: 'Sign NuGet packages'
    inputs:
      ConnectedServiceName: 'CodeSigning-APEX'
      FolderPath: '$(Agent.TempDirectory)/nuget'
      Pattern: '*.nupkg'
      signConfigType: inlineSignParams
      SessionTimeout: 20
      inlineOperation: |
        [
          {
            "KeyCode" : "CP-401405",
            "OperationSetCode" : "NuGetSign",
            "Parameters" : [
                {
                  "parameterName": "TimeStamp",
                  "parameterValue": "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                },
                {
                  "parameterName": "FileDigest",
                  "parameterValue": "/fd \"SHA256\""
                }
            ],
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          },
          {
            "KeyCode" : "CP-401405",
            "OperationSetCode" : "NuGetVerify",
            "Parameters" : [],
            "ToolName" : "sign",
            "ToolVersion" : "1.0"
          }
        ]

  - publish: $(Agent.TempDirectory)/nuget
    artifact: nuget

  - powershell: dotnet nuget push $(Agent.TempDirectory)\nuget\*.nupkg --api-key $env:NUGETAPIKEY --source https://nuget.org
    displayName: dotnet nuget push
    env:
      NUGETAPIKEY: $(NugetAPIKey)